apiVersion: v1
kind: ConfigMap
metadata:
  name: v20-enhance-sprint-retrospectives-sql-cm
  namespace: dsm
data:
  V20__enhance_sprint_retrospectives_table.sql: |
    ALTER TABLE sprint_retrospectives
    ADD COLUMN sprint_name TEXT,
    ADD COLUMN start_date DATE,
    ADD COLUMN end_date DATE,
    ADD COLUMN duration_weeks INTEGER,
    ADD COLUMN tasks_summary JSONB;