apiVersion: v1
kind: ServiceAccount
metadata:
  name: sprint-report-generator-sa
  namespace: dsm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sprint-report-generator-role
  namespace: dsm
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sprint-report-generator-rb
  namespace: dsm
subjects:
- kind: ServiceAccount
  name: sprint-report-generator-sa
  namespace: dsm
roleRef:
  kind: Role
  name: sprint-report-generator-role
  apiGroup: rbac.authorization.k8s.io