apiVersion: batch/v1
kind: Job
metadata:
  name: debug-sprint-status-job
  namespace: dsm
spec:
  template:
    spec:
      containers:
      - name: debug-runner
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Attempting to get sprints for project TEST-001..."
            curl -s http://sprint-service.dsm.svc.cluster.local/sprints/by-project/TEST-001
      restartPolicy: Never
  backoffLimit: 0