apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-chronicle-pv-v17-vector
  namespace: dsm
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs/k8s/gt/chronicle-db-data-v17-vector
    server: 10.204.32.7
  claimRef:
    name: postgres-chronicle-pvc-v17-vector
    namespace: dsm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-chronicle-pvc-v17-vector
  namespace: dsm
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
