apiVersion: v1
kind: Service
metadata:
  name: chronicle-db-v17-vector-svc
  namespace: dsm
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: chronicle-db-v17-vector
