apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-pv
  namespace: dsm
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs/k8s/gt/backup-data
    server: 10.204.32.7
  claimRef:
    name: backup-pvc
    namespace: dsm
