apiVersion: batch/v1
kind: Job
metadata:
  name: restore-job
  namespace: dsm
spec:
  template:
    spec:
      containers:
      - name: restore
        image: postgres:17
        command: ["/bin/sh", "-c"]
        args:
        - "psql --host=chronicle-db-v17-svc --username=chronicle_user --dbname=chronicle_db --file=/backup/dump.sql"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-chronicle-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      restartPolicy: Never
  backoffLimit: 4
