apiVersion: batch/v1
kind: Job
metadata:
  name: backlog-db-check
  namespace: dsm
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:latest
        command: ["bash", "-c"]
        args:
          - |
            PGPASSWORD=$(POSTGRES_PASSWORD) psql -h backlog-db -U dsm_user -d backlog_db -c "\dt"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backlog-db-secret
              key: POSTGRES_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
