apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
  namespace: dsm
spec:
  template:
    spec:
      containers:
      - name: backup
        image: postgres:17
        command: ["/bin/sh", "-c"]
        args:
        - "cp /config/backup-script.sh /tmp/backup-script.sh && chmod +x /tmp/backup-script.sh && /tmp/backup-script.sh"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-chronicle-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: backup-script
          mountPath: /config
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: backup-script
        configMap:
          name: backup-script-config
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      restartPolicy: Never
  backoffLimit: 4
