apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-queries
  namespace: dsm
data:
  queries.yaml: |
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
      master: true
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Disk space used by the database"
    
    agent_memory_episodes:
      query: "SELECT COUNT(*) as total, COUNT(outcome_quality) as with_outcome FROM agent_episodes"
      master: true
      cache_seconds: 30
      metrics:
        - total:
            usage: "GAUGE"
            description: "Total episodes"
        - with_outcome:
            usage: "GAUGE"
            description: "Episodes with outcomes"