apiVersion: v1
kind: ServiceAccount
metadata:
  name: failing-jobs-checker-sa
  namespace: dsm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: failing-jobs-checker-role
  namespace: dsm
rules:
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: failing-jobs-checker-rb
  namespace: dsm
subjects:
- kind: ServiceAccount
  name: failing-jobs-checker-sa
  namespace: dsm
roleRef:
  kind: Role
  name: failing-jobs-checker-role
  apiGroup: rbac.authorization.k8s.io
