apiVersion: v1
kind: Service
metadata:
  name: backlog-db
  namespace: dsm
spec:
  selector:
    app: backlog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
