apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-data
  namespace: dsm
  labels: {"appid":"postgres", "env":"dev", "app-svc":"postgres"}
spec:
  storageClassName: nfs-client
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/k8s/gt/db-data
    server: 10.204.32.7
    readOnly: false
  claimRef:
    name: postgres-pvc
    namespace: dsm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dsm
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi